### PR TITLE
resimulate invalid cycle parameters

### PR DESCRIPTION
**Pull request by srcole**
issue #124

The script in this issue now runs and throws the following warning:

```
/gh/bv/neurodsp/neurodsp/sim.py:244: UserWarning: A cycle was simulated with invalid feature(s) for:
                        **amp ** (e.g. less than 0). A new cycle was
                        simulated to replace it. If this warning appears often, you should
                        change your simulation parameters.
  change your simulation parameters.'''.format(features_invalid))
/gh/bv/neurodsp/neurodsp/sim.py:244: UserWarning: A cycle was simulated with invalid feature(s) for:
                        **rdsym ** (e.g. less than 0). A new cycle was
                        simulated to replace it. If this warning appears often, you should
                        change your simulation parameters.
  change your simulation parameters.'''.format(features_invalid))
```

I think this is good. Because invalid parameters were only simulated twice during a 100 second simulation of 10Hz oscillation, resimulating a couple times won’t bias the distribution much at all.

### CODE REVIEW

**Comment by rdgao** [comment]
```
period = current_burst_period_mean + \
                np.random.randn() * cycle_features_use['period_std']
amp = current_burst_amp_mean + \
                np.random.randn() * cycle_features_use['amp_std']
rdsym = current_burst_rdsym_mean + \
                np.random.randn() * cycle_features_use['rdsym_std']
```

this is what it was before, and I realized we can't just replace with truncnorm at 0 because that will cut the standard normal draw in half.

What we actually want to do is probably just take use `max(0.,amp)`?

**Comment by rdgao** [comment]
alright I'm actually not 100% sure what to do here: 

If we clip any of those 3 values at 0 after the appropriate scaling, and the cycle is set to be oscillating, does it screw up the data generation for that cycle later in the code. E.g., if period is 0? 

Do period, amp, and rdsym affect the subsequent cycle generation differently if they were 0?

If clipping at 0 is not okay, perhaps we should flip that cycle to be NOT oscillating if any of the params generate invalid values? Or have them take on another (default) value?

I still don't think having a while loop here is the best idea, as it could significantly increase run time. One option is to try 5 times and if the values are still invalid, error out and make the user change the arg values.

**Comment by srcole** [comment]
I would opt for the last option you mentioned. If after 5 tries, we're still having problems, then the input parameters are funky.

Then we can return to them that we were commonly simulating negative values for feature _____. And tell them to perhaps modify the mean and st dev so that the defined distribution does not fall below 0 much

**Comment by srcole** [comment]
Right, I could see maybe the user would want to modify it to 1 (or 0, depending on how it's coded), if they wanted to be very strict that the simulated distribution matches the defined one

**Comment by rdgao** [comment]
sounds good

**Comment by rdgao** [comment]
closing this, see PR #128

**Pull request closed without merging**
