### PR TITLE
Plts and compute_burst_stats tests

### PR DESCRIPTION
**Pull request by srcole**
partial issue #91

### CODE REVIEW

**Comment by srcole** [comment]
Not really sure why 3.4 is failing.

Can we just drop 3.4 from our tests and only support 3.5+

3.4 has started to give us a few misc problems.

**Comment by TomDonoghue** [comment]
I dropped 3.4 on FOOOF, because I was using some things (simple string manipulation stuff) that wasn't supported in 3.4. Doesn't seem to have been a problem / no one has complained - so if you want to change the listed Python versions in setup.py, and stop it running on travis, I think that would be fine!

**Comment by TomDonoghue** [comment]
Also - throw an eye on .travis in FOOOF to see how to add testing of 3.7 (for some dumb reason it's a bit different than normal, but we might as well test the newest version).

**Comment by rdgao** [comment]
alright I'm gonna merge this and test 3.7 on a different PR

**Pull request merged**
