### PR TITLE
Update naming

### PR DESCRIPTION
**Pull request by TomDonoghue**
Responds to #82 - update all the names.

Opened the PR to see if/what conflicts with other changes going in. 

Edit: should be pretty much there. I didn't bother with the tests, for now.

### CODE REVIEW

**Comment by srcole** [comment]
Just scrolled through it. Good shit, Tom. Thanks so much for going through and improving all that naming!
Was there anything else you wanted to do?
I think it's good to merge.

**Comment by rdgao** [comment]
yep, looks good to me. MVP effort.

**Comment by TomDonoghue** [comment]
I did a last check on the tests last night too. From my perspective this should be good

Because so much code has changed, this is a PR that could use a bit of pushing on - if you want to clone this branch, and check that you can run things without anything changing, that would probably be good. I did also change more names than were explicitly mentioned in #82, so double check I didn't change anything that will annoy you :). 

After that, should be good to merge. This PR does fundamentally break consistency on master, so whenever people clone from now on, related code will need to be updated.

**Comment by srcole** [comment]
The only thing I can think of is that we still have to change the orders of inputs in `sim.py` so that they're consistent across functions, as mentioned in issue #67. But I think that can be done in another PR to close this issue.

This is it for issue #82 , right?

And since all the tests pass that check for consistency with previous versions of the code, I think that tests pretty well that nothing has functionally changed. So I think it's good to merge. And then we can quickly tackle the rest of the issues before releasing 1.0

**Pull request merged**
