### PR TITLE
Move plots to their own file

### PR DESCRIPTION
**Pull request by TomDonoghue**
WIP for #81 

What is here should be good. 

To do:
- Do we want to add tests for plots?
- Need to double check docs, maybe some updates there. 
- Do we wants to have a flat plts file, as is, or a folder of plot related things, so it would be (for example) `from ndsp.plts.spectral import plot_spectra`. This might have a cleaner organization in the long run.

### CODE REVIEW

**Comment by srcole** [comment]
I think smoke tests for plots are good. But nothing more than that. Just show them in the tutorials.

**Comment by rdgao** [comment]
separate plotting folder would be nice, actually. 

We don't have a lot of stuff right now, but I feel like thinking ahead would be beneficial so we don't have to go through this whole exercise again down the road.

**Comment by TomDonoghue** [comment]
Yeh - agreed on having a folder, I'll update to that. 

Tests: yeh, I usually have tests that the plots at least run (don't really check what they plot, that's a bit hard). 

I'll update these.

**Comment by TomDonoghue** [comment]
@srcole & @rdgao 

Can we merge this, and I'll make a separate PR on folder & tests?

Only reason - 'names' branched of here, so could be a conflict if they both go on separate paths when we try to bring them together again.

**Pull request merged**
