### PR TITLE
added variable 1/f exponent simulation

### PR DESCRIPTION
**Pull request by rdgao**
#67

### CODE REVIEW

**Comment by rdgao** [comment]
@srcole @TomDonoghue failing for 3.6 here, but not on my machine. You guys had this problem very recently right?

**Comment by srcole** [comment]
right. I think we should just undo some of the setup.py changes in PR#66 until it doesn't fail anymore. and then re-investigate later

**Comment by rdgao** [comment]
okay, sounds good. So should I just merge here?

**Comment by srcole** [comment]
i think it makes sense for me to make a quick PR to undo the setup.py stuff and merge it. and then you can get that update in your PR and we can make sure that travis is OK with everything you changed

**Comment by rdgao** [comment]
oui tres bien

**Pull request merged**
